# src/lib/constants.py

# HTTP Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_NO_CONTENT = 204
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500

# Auth
SESSION_COOKIE_NAME = "session"
SESSION_MAX_AGE_SECONDS = 86400  # 24 hours

# Database
DATABASE_PATH = "sqlite.db"
